name: Build APK Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Ferramentas de Build
        run: |
          sudo apt-get update
          # Mudamos aqui: instalando as build-tools que já trazem o aapt2
          sudo apt-get install -y google-android-build-tools-34.0.0-installer || sudo apt-get install -y aapt
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.10.0/apktool_2.10.0.jar -O apktool.jar

      - name: Compilar APK (Pasta GB)
        # Forçamos o uso do aapt interno do apktool para evitar erros de caminho
        run: java -jar apktool.jar b GB -o gamebooster_mod.apk

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: LagSwitch-Mod-APK
          path: gamebooster_mod.apk
